# Secret will be automatically created by cert-manager Certificate resource
# Self-signed certificate for development
# For production, use proper CA-signed certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway-cert
  namespace: istio-system
spec:
  secretName: istio-tls-cert
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.example.com"
  - "example.com"
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
    - "EKS Cluster"
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048